version: "3"
services:    
    server:
        container_name: server
        build:
            context: ./server
                # volumes
        depends_on:
            - mongo
        volumes:
            - ".:/home/app/server"
        # command: >
        #     bash
        stdin_open: true # docker run -i
        tty: true # docker run -t
        ports : 
            - 8080:8080

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/